apiVersion: v1
kind: Service
metadata:
  name: hunter-sim-service
  namespace: hunter-sim
spec:
  selector:
    app: hunter-sim
    component: sim-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
